language: python

python:
  - "3.7"

before_script:
  - cd NUTELLA/
  - pip install -r requirements.txt

# safelist
branches:
  only:
    - staging
    
env: DJANGO_SETTINGS_MODULE="nutella_stop.settings.travis"

services:
  - postgresql

script:
  - python3 manage.py test


