# Generated by Django 3.0.2 on 2020-02-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200203_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_off',
            field=models.URLField(unique=True),
        ),
    ]
